### ISSUE TITLE
ChromeDriver.exe

### ISSUE THREAD

**Issue by oblivibird** [Addy32/defendkids-website-spammer#4]
`chromedriver.exe` must match the installed chrome version for the program to run. Additional chromedriver versions can be found [here](https://chromedriver.storage.googleapis.com/index.html?path=107.0.5304.62/). I think it would help to add this to `readme.md`.

**Comment by Addy32** [comment]
I don't think the chromed river package does anything since I'm using the undetected_chromedriver package
